### ISSUE TITLE
Missing functionality?

### ISSUE THREAD

**Issue by chrisdotcode** [calculist/calculist-desktop#3]
Hi, I just discovered calculist, and it seems awesome. However, downloading+installing the app (Linux) seems to be missing either a lot of features/and or a list of keybindings.

What seems to be available in the app is the ability to create, move and expand/collapse lists. I don't know how to/it don't seem to have the ability to access command mode, zoom in, mark items as finished, etc..

Are these functionalities hidden behind keybindings (unfortunately, there's no list of keybinding in the app, either), or not yet implemented on the desktop app as of yet?

Calculist seems pretty cool from the video, and I'd be glad to help if I can :slightly_smiling_face:

**Comment by danallison** [comment]
Hi @chrisdotcode . The desktop app uses the same code as the web app, so there should be no missing functionality. However, I am embarrassed to admit that it is not obvious how to use the app, or even how to figure out how to use the app. Once I wrap up my current work-in-progress and ship v0.3.0, I will be shifting my focus to writing documentation, tutorials, and making the app easier to use.

In the meantime, current documentation can be found at https://github.com/calculist/calculist/wiki and keyboard shortcut specific documentation can be found at https://github.com/calculist/calculist/wiki/Keyboard-Shortcuts .

The shortcut to enter command mode is `ctrl + enter` (you can also double click an item) and the shortcuts for zooming are `ctrl + right arrow` to zoom in and `ctrl + left arrow` to zoom out. Unfortunately, keybindings are not yet customizeable in the desktop app, but that will be changing soon.

Lastly, thanks for offering to help. Contributions are definitely welcome. I'm planning to add more developer-specific documentation and contribution guides soon. In general, there's a lot of organizing and documenting that I need to do to make it easier for others to use/develop the app. Feel free to ask questions. If there's a specific feature or bug you'd like to work on, I'd be happy to point you in the right direction.

**Comment by chrisdotcode** [comment]
Thanks! Nothing specific at the moment, but if I find something while using calculist, I'll let it be known :+1:
